# Generated by Django 4.2.3 on 2023-07-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailmodel',
            name='date_joined',
        ),
    ]
