# Generated by Django 4.2.3 on 2023-07-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_userdetailmodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='address1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='address2',
            field=models.CharField(max_length=500),
        ),
    ]
