# Generated by Django 4.2.3 on 2023-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flightmodel_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_id',
            field=models.CharField(default='YSEJH4', max_length=6, null=True, unique=True),
        ),
    ]
