# Generated by Django 4.2.3 on 2023-08-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flightmodel_flight_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.usermodel')),
            ],
        ),
    ]
